CC=gcc
CFLAGS=-I.

parallel_min_max : utils.o find_min_max.o utils.h find_min_max.h
	$(CC) -o parallel_min_max.o utils.o find_min_max.o parallel_min_max.c $(CFLAGS)

utils.o : utils.h
	$(CC) -o utils.o -c utils.c $(CFLAGS)

find_min_max.o : utils.h find_min_max.h
	$(CC) -o find_min_max.o -c find_min_max.c $(CFLAGS)

res2: utils.o utils.h
	$(CC) -o res2 utils.o parallel_sum.c -lpthread

process_memory:
	$(CC) -o process_memory process_memory.c

clean :
	rm parallel_min_max res2